version: '3.1'

services:

  web:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    image: uvicscheduler-client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: uvicscheduler-server
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      FLASK_APP: app.py
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./scripts/uvicscheduler.sql:/scripts/uvicscheduler.sql
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: uvicscheduler
    env_file: ./docker/.env

  adminer:
    image: adminer
    ports:
      - 8080:8080